version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  linting:
    docker:
      - image: python:3.7-alpine3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl nginx
  build:
    docker:
      - image: alpine:3.14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl nginx
      - run:
          name: copy configuration
          command: |
            cp -f nginx.conf /etc/nginx/nginx.conf
            cat /etc/nginx/nginx.conf
      - run:
          name: copy app
          command: |
            cp -r ./www /www
            cat /www/index.html
      - run:
          name: start server
          command: |
            nginx
      - run:
          name: linting
          command: |
            nginx -c ~/repo/nginx.conf -t
      - run:
          name: Run test
          command: |
            if curl -s localhost | grep "Elwy"
            then
              return 0
            else
              return 1
            fi

  build_and_push_image:
    machine: true
    steps:
      - aws-ecr/build-and-push-image:
          create-repo: true
          region: AWS_DEFAULT_REGION
          no-output-timeout: 20m
          profile-name: admin
          repo: testblueimage
          tag: 'latest,myECRRepoTag'

  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.json
          resource-name: deployment/blue
          show-kubectl-command: true
  create-service:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: service.json
          resource-name: service/bluegreenlb
  create-small-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run:
          name: install eksctl tool
          command: |
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
            | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            sudo mv eksctl_download/eksctl /bin/eksctl
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ''
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          skip-kubectl-install: false
          verbose: 3
          node-type: t3.small
          nodes-max: 2
          ssh-access: false
          ssh-public-key: ''

workflows:
  default:
    jobs:
      - linting
      - build:
          requires: [linting]
      - build_and_push_image:
          requires: [build]
#      - create-small-cluster:
#          cluster-name: eks-demo-deployment
#          requires: [ build_and_push_image]
#      - create-service:
#          cluster-name: eks-demo-deployment
#          requires:
#            - create-small-cluster
      - create-deployment:
          cluster-name: eks-demo-deployment
          requires:
#            - create-service
      - aws-eks/update-container-image:
          cluster-name: eks-demo-deployment
          container-image-updates: 'blue=elwy/testblueimage:latest'
          record: true
          requires:
            - create-deployment
          resource-name: deployment/blue