version: 2
jobs:
  build:
    docker:
      - image: alpine:3.14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl nginx
            cp -f nginx.conf /etc/nginx/nginx.conf
            cp -r ./www /www
            nginx
             if curl -s localhost | grep "Elwy"
            then
              return 0
            else
              return 1
            fi