version: 2
jobs:
  build:
    docker:
      - image: alpine:3.14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl nginx
            cp ./www /www