version: 2
jobs:
  build:
    docker:
      - image: alpine:3.14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl nginx
      - run:
          name: copy configuration
          command: |
            cp -f nginx.conf /etc/nginx/nginx.conf
            cat /etc/nginx/nginx.conf
      - run:
          name: copy app
          command: |
            cp -r ./www /www
            cat /www/index.html
      - run:
          name: start server
          command: |
            nginx
      - run:
          name: Run test
          command: |
            if curl -s localhost | grep "Elwy"
            then
              return 0
            else
              return 1
            fi
workflows:
  default:
    jobs:
      - build
      - deploy-infrastructure:
          requires: [build]